#!/bin/bash
# Stops accidental commits to master and develop. https://gist.github.com/stefansundin/9059706
# Install:
# cd path/to/git/repo
# curl -fL -o .git/hooks/pre-commit https://gist.githubusercontent.com/stefansundin/9059706/raw/pre-commit-2
# chmod +x .git/hooks/pre-commit

remote="$1"
url="$2"

function no-push-in-master-or-develop-branch() {
    BRANCH=`git rev-parse --abbrev-ref HEAD`

    if [[ "$BRANCH" == "master" || "$BRANCH" == "develop" ]]; then
	      echo >&2 "You are on branch $BRANCH. Are you sure you want to commit to this branch?"
	      echo >&2 "If so, commit with -n to bypass this pre-commit hook."
	      exit 1
    fi

}

function no-wip-commits() {

    if git log -10 --oneline | grep "\-\-wip\-\-" >/dev/null ; then
	      echo >&2 "--wip-- in commits! Abort!"
	      exit 1
    fi

}

no-push-in-master-or-develop-branch
no-wip-commits

exit 0
