#!/bin/sh
# author: Igor Avdeev
# description: Creates

if ! head -n 1 $1 | grep -E "C[0-9]+-[0-9]+" ; then
    BRANCH_NAME=$(git branch | grep '*' | grep -oE "C[0-9]+-[0-9]+")
    if [[ "$BRANCH_NAME" ]] ; then
        OLD=$(cat "$1")
        echo -n "" > "$1"
        echo -n "[" >> "$1"
        echo -n  >> "$1"
        echo -n "] " >> "$1"
        echo "$OLD" >> "$1"
    fi
fi
